WebApplication1/Controllers/AdminPanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class AdminPanelController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AdminPanelController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var completedCount = _context.PassportApplication.Count(pa => pa.ApplicationStatus == "Completed");
            var awaitingAcceptanceCount = _context.PassportApplication.Count(pa => pa.ApplicationStatus == "Awaiting acceptance");

            ViewData["CompletedCount"] = completedCount;
            ViewData["AwaitingAcceptanceCount"] = awaitingAcceptanceCount;

            return View();
        }

    }

}

WebApplication1/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;
using X.PagedList;

namespace WebApplication1.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        public EmployeesController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(int? page)
        {
            int pageNumber = page ?? 1;
            int pageSize = 10;

            var employees = await _context.Employees.ToPagedListAsync(pageNumber, pageSize);
            return View(employees);
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeesId == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            var existingUserIds = _context.Employees
                .Where(e => !string.IsNullOrEmpty(e.UserId))
                .Select(e => e.UserId)
                .ToList();

            var users = _userManager.Users
                .Where(u => !existingUserIds.Contains(u.Id))
                .Select(u => new { u.Id, u.Email })
                .ToList();

            ViewData["UserId"] = new SelectList(users, "Id", "Email");
            return View();
        }


        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("EmployeesId,EmployeeName,EmployeeSurname,UserId")] Employees employees)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employees);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            var users = _userManager.Users.Select(u => new { u.Id, u.Email }).ToList();
            ViewData["UserId"] = new SelectList(users, "Id", "Email", employees.UserId);
            return View(employees);
        }





        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees.FindAsync(id);
            if (employees == null)
            {
                return NotFound();
            }
            return View(employees);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EmployeesId,EmployeeName,EmployeeSurname,EmployeePosition")] Employees employees)
        {
            if (id != employees.EmployeesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeesExists(employees.EmployeesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employees);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.EmployeesId == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employees = await _context.Employees.FindAsync(id);
            if (employees != null)
            {
                _context.Employees.Remove(employees);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeesExists(int id)
        {
            return _context.Employees.Any(e => e.EmployeesId == id);
        }
    }
}

WebApplication1/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Data;
using WebApplication1.Models;
using X.PagedList;


namespace WebApplication1.Controllers
{
    public class PeopleController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PeopleController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: People
        // GET: People
        public async Task<IActionResult> Index(int? page, string sortOrder, string searchString)
        {
            const int pageSize = 10;

            var applicationDbContext = _context.Person.Include(p => p.BirthPlace).Include(p => p.RegistrationPlace).AsQueryable();

            ViewData["DefaultSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["SurnameSortParm"] = sortOrder == "surname" ? "surname_desc" : "surname";
            ViewData["DateOfBirthSortParm"] = sortOrder == "DateOfBirth" ? "DateOfBirth_desc" : "DateOfBirth";

            ViewData["CurrentSort"] = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                applicationDbContext = applicationDbContext.Where(p => p.PersonSurname.Contains(searchString) || p.PersonName.Contains(searchString));
            }

            var people = from p in _context.Person
                         select p;

            switch (sortOrder)
            {
                case "name_desc":
                    people = people.OrderByDescending(p => p.PersonName);
                    break;
                case "Surname":
                    people = people.OrderBy(p => p.PersonSurname);
                    break;
                case "surname_desc":
                    people = people.OrderByDescending(p => p.PersonSurname);
                    break;
                case "DateOfBirth":
                    people = people.OrderBy(p => p.PersonDateOfBirth);
                    break;
                case "dateOfBirth_desc":
                    people = people.OrderByDescending(p => p.PersonDateOfBirth);
                    break;
                // Add more cases for other fields
                default:
                    people = people.OrderBy(p => p.PersonName);
                    break;
            }

            int pageNumber = page ?? 1;
            var pagedModel = await applicationDbContext.ToPagedListAsync(pageNumber, pageSize);

            return View(pagedModel);
        }



        // GET: People/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .Include(p => p.RegistrationPlace)
                .Include(p => p.BirthPlace)
                .Include(p => p.PersonPassport)
                .FirstOrDefaultAsync(m => m.PersonId == id);

            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PersonId,PersonName,PersonSurname,PersonSex,PersonDateOfBirth,PersonNationality,RNKNumber,RegistrationPlaceId,BirthPlaceId,PersonPassportId")] Person person)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (person.RegistrationPlace == null)
                    {
                        person.RegistrationPlace = new RegistrationPlaces();
                        _context.RegistrationPlaces.Add(person.RegistrationPlace);
                        await _context.SaveChangesAsync();
                    }

                    // Check if the person has a birth place
                    if (person.BirthPlace == null)
                    {
                        person.BirthPlace = new PlacesOfBirth();
                        _context.PlacesOfBirth.Add(person.BirthPlace);
                        await _context.SaveChangesAsync();
                    }

               
                    _context.Person.Add(person);
                    await _context.SaveChangesAsync();

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error creating the record. Please contact the administrator.";
            }

            ViewBag.ErrorMessage = TempData["ErrorMessage"];

            return View("Create", person);
        }



        // POST: People/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                var person = await _context.Person.FindAsync(id);
                if (person == null)
                {
                    return NotFound();
                }

                person.BirthPlace = await _context.PlacesOfBirth.FindAsync(person.BirthPlaceId);
                person.RegistrationPlace = await _context.RegistrationPlaces.FindAsync(person.RegistrationPlaceId);

                ViewData["BirthPlaceId"] = new SelectList(_context.PlacesOfBirth, "BirthPlaceId", "BirthPlaceId", person.BirthPlaceId);
                ViewData["RegistrationPlaceId"] = new SelectList(_context.RegistrationPlaces, "RegistrationPlaceId", "RegistrationPlaceId", person.RegistrationPlaceId);
                return View(person);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while trying to fetch the person for editing. Please try again.");

                return RedirectToAction();
            }
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
            {
                return NotFound();
            }

            try
            {
                var person = await _context.Person
                    .Include(p => p.BirthPlace)
                    .Include(p => p.RegistrationPlace)
                    .FirstOrDefaultAsync(m => m.PersonId == id);

                if (person == null)
                {
                    return NotFound();
                }

                if (await TryUpdateModelAsync(person, "",
                    p => p.PersonName, p => p.PersonSurname, p => p.PersonSex,
                    p => p.PersonDateOfBirth, p => p.PersonNationality, p => p.RNKNumber,
                    p => p.RegistrationPlace, p => p.BirthPlace, p => p.PersonPassportId))
                {
                    // Оновлення пов'язаних об'єктів
                    _context.RegistrationPlaces.Update(person.RegistrationPlace);
                    _context.PlacesOfBirth.Update(person.BirthPlace);

                    // Оновлення основного об'єкта
                    _context.Person.Update(person);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }

                ViewData["BirthPlaceId"] = new SelectList(_context.PlacesOfBirth, "BirthPlaceId", "City", person.BirthPlaceId);
                ViewData["RegistrationPlaceId"] = new SelectList(_context.RegistrationPlaces, "RegistrationPlaceId", "City", person.RegistrationPlaceId);
                return View(person);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, "An error occurred while trying to update the person. Please try again.");

                return RedirectToAction();
            }
        }

        // GET: People/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var person = await _context.Person
                .Include(p => p.BirthPlace)
                .Include(p => p.RegistrationPlace)
                .FirstOrDefaultAsync(m => m.PersonId == id);
            if (person == null)
            {
                return NotFound();
            }

            return View(person);
        }

        // POST: People/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var person = await _context.Person
                    .Include(p => p.PersonPassport) 
                    .FirstOrDefaultAsync(m => m.PersonId == id);

                if (person == null)
                {
                    return NotFound();
                }

                if (person.PersonPassport != null)
                {
                    _context.PersonPassports.Remove(person.PersonPassport);
                }

                _context.Person.Remove(person);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = "Error while deleting the person";
                return RedirectToAction(nameof(Index));
            }
        }



        private bool PersonExists(int id)
        {
            return _context.Person.Any(e => e.PersonId == id);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Passport Office</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                    
                        
                        @if (User.IsInRole("Manager") || User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassportApplications" asp-action="Index">Order service</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">Persones</a>
                            </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Emploees</a>
                            </li>
                               <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassportServices" asp-action="Index">Passport Services</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AdminPanel" asp-action="Index">Admin Panel</a>
                            </li>
                        }
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Passport Office</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_PagingPartial.cshtml
@model X.PagedList.IPagedList

<div class="pagination-container">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            <li class="page-item @(Model.PageNumber == 1 ? "disabled" : "")">
                <a class="page-link" href="@Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page = 1 })" aria-label="First">
                    <span aria-hidden="true">&laquo;&laquo;</span>
                </a>
            </li>
            <li class="page-item @(Model.PageNumber == 1 ? "disabled" : "")">
                <a class="page-link" href="@Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page = Model.PageNumber - 1 })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            @for (var i = 1; i <= Model.PageCount; i++)
            {
                <li class="page-item @(Model.PageNumber == i ? "active" : "")">
                    <a class="page-link" href="@Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page = i })">@i</a>
                </li>
            }

            <li class="page-item @(Model.PageNumber == Model.PageCount ? "disabled" : "")">
                <a class="page-link" href="@Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page = Model.PageNumber + 1 })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
            <li class="page-item @(Model.PageNumber == Model.PageCount ? "disabled" : "")">
                <a class="page-link" href="@Url.Action(ViewContext.RouteData.Values["action"].ToString(), new { page = Model.PageCount })" aria-label="Last">
                    <span aria-hidden="true">&raquo;&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

WebApplication1/Views/Shared/_SearchFormPatial.cshtml
@model string

<form asp-action="Index" method="get" class="d-flex">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@Model" />
            <input type="submit" value="Search" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-secondary">Back to Full List</a>
        </p>
    </div>
</form>